# Copyright 2025 Atakku <https://atakku.dev>
#
# This project is dual licensed under MIT and Apache.

[package]
name = "aku_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
paste.workspace = true
extend.workspace = true
